/** This generator replaces all model `Date` types with `UtcIsoString` types. */

import {addRegExpFlags, awaitedForEach, log} from '@augment-vir/common';
import {joinFilesToDir, readDirRecursive} from '@augment-vir/node';
import generatorHelper from '@prisma/generator-helper';
import {readFile, writeFile} from 'node:fs/promises';
import {relative} from 'node:path';
import {generatorVersion, resolveGeneratorOutput} from './generator-util.js';

type Replacement = {
    match: RegExp | string;
    replace: string;
};

const replacements: Replacement[] = [
    {
        match: /\bDate\s*\|\s*string\b/,
        replace: 'UtcIsoString',
    },
    {
        match: /\bstring\s*\|\s*Date\b/,
        replace: 'UtcIsoString',
    },
    {
        match: /\bDate\b/,
        replace: 'UtcIsoString',
    },
    {
        match: /\/\/\s*@ts-nocheck\s*/,
        replace: '',
    },
];

const insertAtTop = [
    '// @ts-nocheck',
    "import {type UtcIsoString} from 'date-vir';",
];

generatorHelper.generatorHandler({
    onManifest() {
        return {
            version: generatorVersion,
            defaultOutput: '../src/generated',
            prettyName: 'String Dates',
        };
    },
    async onGenerate(options) {
        const outputDir = resolveGeneratorOutput(options.generator.output);

        const filePathsToFix = joinFilesToDir(outputDir, await readDirRecursive(outputDir));

        await awaitedForEach(filePathsToFix, async (filePath) => {
            /** Don't fix files generated by us. */
            if (filePath.endsWith(`.gen.ts`)) {
                return;
            }

            if (!filePath.endsWith('.ts')) {
                return;
            }
            log.faint(`Using date strings in ${relative(process.cwd(), filePath)}`);

            const contents = String(await readFile(filePath));

            const fixedContent = [
                ...insertAtTop,
                replacements.reduce((value, replacement) => {
                    return value.replaceAll(
                        addRegExpFlags(replacement.match, 'g'),
                        replacement.replace,
                    );
                }, contents),
            ].join('\n');

            await writeFile(filePath, fixedContent);
        });
    },
});
