#!/usr/bin/env node

/**
 * This generator replaces all model `Date` types with `UtcIsoString` types, or with
 * `DateOnlyUtcIsoString` types for `@db.Date` fields.
 */

import {addRegExpFlags, awaitedForEach} from '@augment-vir/common';
import {joinFilesToDir, readDirRecursive} from '@augment-vir/node';
import generatorHelper from '@prisma/generator-helper';
import {readFile, writeFile} from 'node:fs/promises';
import {basename, dirname} from 'node:path';
import {resolveGeneratorOutput} from './generator-util/generator-output.js';
import {generatorVersion} from './generator-util/version.js';

type Replacement = {
    match: RegExp | string;
    replace: string;
    onlyIfChanged?: boolean;
};

const replacements: Replacement[] = [
    {
        match: /\bDate\[\]\s*\|\s*string\[\]/,
        replace: 'UtcIsoString[]',
    },
    {
        match: /\bstring\[\]\s*\|\s*Date\[\]/,
        replace: 'UtcIsoString[]',
    },
    {
        match: /\bDate\s*\|\s*string\b/,
        replace: 'UtcIsoString',
    },
    {
        match: /\bstring\s*\|\s*Date\b/,
        replace: 'UtcIsoString',
    },
    {
        /**
         * Skip object keys and string literals so enum members (`Date: 'Date'`) and fields named
         * `Date` keep their runtime names.
         */
        match: /(?<!['"])\bDate\b(?!['"]|\s*\??:)/,
        replace: 'UtcIsoString',
    },
    {
        match: /\/\/\s*@ts-nocheck\s*/,
        replace: '',
        onlyIfChanged: true,
    },
];

const {alwaysReplace, replaceIfChanged} = replacements.reduce(
    (accum, current) => {
        if (current.onlyIfChanged) {
            accum.replaceIfChanged.push(current);
        } else {
            accum.alwaysReplace.push(current);
        }
        return accum;
    },
    {
        alwaysReplace: [] as Replacement[],
        replaceIfChanged: [] as Replacement[],
    },
);

const dateOnlyReplacements: Replacement[] = alwaysReplace.map((replacement) => {
    return {
        ...replacement,
        replace: replacement.replace.replace('UtcIsoString', 'DateOnlyUtcIsoString'),
    };
});

generatorHelper.generatorHandler({
    onManifest() {
        return {
            version: generatorVersion,
            defaultOutput: '../src/generated',
            prettyName: 'String Dates',
        };
    },
    async onGenerate(options) {
        const outputDir = resolveGeneratorOutput(options.generator.output);

        const filePathsToFix = joinFilesToDir(outputDir, await readDirRecursive(outputDir));

        await awaitedForEach(filePathsToFix, async (filePath) => {
            if (
                /** Don't fix files generated by us. */
                filePath.endsWith('.gen.ts') ||
                /** Only modify TS files. */
                !filePath.endsWith('.ts')
            ) {
                return;
            }

            const contents = String(await readFile(filePath));

            const modelName =
                basename(dirname(filePath)) === 'models' ? basename(filePath, '.ts') : undefined;
            const dateOnlyFieldNames =
                options.dmmf.datamodel.models
                    .find((model) => model.name === modelName)
                    ?.fields.filter((field) => field.nativeType?.[0] === 'Date')
                    .map((field) => field.name) || [];

            const definitelyReplaced = applyReplacements(
                applyDateOnlyReplacements(contents, dateOnlyFieldNames),
                alwaysReplace,
            );

            if (contents === definitelyReplaced) {
                /** No changes were made. */
                return;
            }
            const conditionallyReplaced = applyReplacements(definitelyReplaced, replaceIfChanged);

            const fixedContent = [
                '// @ts-nocheck',
                conditionallyReplaced.includes('DateOnlyUtcIsoString')
                    ? "import {type DateOnlyUtcIsoString, type UtcIsoString} from 'date-vir';"
                    : "import {type UtcIsoString} from 'date-vir';",
                conditionallyReplaced,
            ].join('\n');

            await writeFile(filePath, fixedContent);
        });
    },
});

function applyReplacements(original: string, replacements: ReadonlyArray<Readonly<Replacement>>) {
    return replacements.reduce((value, replacement) => {
        return value.replaceAll(addRegExpFlags(replacement.match, 'g'), replacement.replace);
    }, original);
}

/** Applies {@link dateOnlyReplacements} only to the type lines of the given fields. */
function applyDateOnlyReplacements(original: string, fieldNames: ReadonlyArray<string>) {
    if (!fieldNames.length) {
        return original;
    }

    return original.replaceAll(
        new RegExp(String.raw`^\s*(?:${fieldNames.join('|')})\??:.*$`, 'gm'),
        (line) => applyReplacements(line, dateOnlyReplacements),
    );
}
