/** This generator replaces all model `Date` types with `UtcIsoString` types. */

import {addRegExpFlags, awaitedForEach, log} from '@augment-vir/common';
import {joinFilesToDir, readDirRecursive} from '@augment-vir/node';
import generatorHelper from '@prisma/generator-helper';
import {readFile, writeFile} from 'node:fs/promises';
import {relative} from 'node:path';
import {generatorVersion, resolveGeneratorOutput} from './generator-util.js';

type Replacement = {
    match: RegExp | string;
    replace: string;
    onlyIfChanged?: boolean;
};

const replacements: Replacement[] = [
    {
        match: /\bDate\[\]\s*\|\s*string\[\]/,
        replace: 'UtcIsoString[]',
    },
    {
        match: /\bstring\[\]\s*\|\s*Date\[\]/,
        replace: 'UtcIsoString[]',
    },
    {
        match: /\bDate\s*\|\s*string\b/,
        replace: 'UtcIsoString',
    },
    {
        match: /\bstring\s*\|\s*Date\b/,
        replace: 'UtcIsoString',
    },
    {
        match: /\bDate\b/,
        replace: 'UtcIsoString',
    },
    {
        match: /\/\/\s*@ts-nocheck\s*/,
        replace: '',
        onlyIfChanged: true,
    },
];

const {alwaysReplace, replaceIfChanged} = replacements.reduce(
    (accum, current) => {
        if (current.onlyIfChanged) {
            accum.replaceIfChanged.push(current);
        } else {
            accum.alwaysReplace.push(current);
        }
        return accum;
    },
    {
        alwaysReplace: [] as Replacement[],
        replaceIfChanged: [] as Replacement[],
    },
);

const insertAtTop = [
    '// @ts-nocheck',
    "import {type UtcIsoString} from 'date-vir';",
];

generatorHelper.generatorHandler({
    onManifest() {
        return {
            version: generatorVersion,
            defaultOutput: '../src/generated',
            prettyName: 'String Dates',
        };
    },
    async onGenerate(options) {
        const outputDir = resolveGeneratorOutput(options.generator.output);

        const filePathsToFix = joinFilesToDir(outputDir, await readDirRecursive(outputDir));

        await awaitedForEach(filePathsToFix, async (filePath) => {
            if (
                /** Don't fix files generated by us. */
                filePath.endsWith(`.gen.ts`) ||
                /** Only modify TS files. */
                !filePath.endsWith('.ts')
            ) {
                return;
            }

            const contents = String(await readFile(filePath));

            const definitelyReplaced = applyReplacements(contents, alwaysReplace);

            if (contents === definitelyReplaced) {
                /** No changes were made. */
                return;
            }
            const conditionallyReplaced = applyReplacements(definitelyReplaced, replaceIfChanged);

            log.faint(`Using date strings in ${relative(process.cwd(), filePath)}`);

            const fixedContent = [
                ...insertAtTop,
                conditionallyReplaced,
            ].join('\n');

            await writeFile(filePath, fixedContent);
        });
    },
});

function applyReplacements(original: string, replacements: ReadonlyArray<Readonly<Replacement>>) {
    return replacements.reduce((value, replacement) => {
        return value.replaceAll(addRegExpFlags(replacement.match, 'g'), replacement.replace);
    }, original);
}
